-- Generated by Oracle SQL Developer Data Modeler 4.0.3.853
--   at:        2015-05-03 16:47:23 CEST
--   site:      SQL Server 2008
--   type:      SQL Server 2008




CREATE
  TABLE Category
  (
    idCategory INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    name       VARCHAR (100) NOT NULL ,
    description NVARCHAR (MAX) ,
    CONSTRAINT Category_PK PRIMARY KEY CLUSTERED (idCategory)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Category__IDX ON Category
(
  idCategory
)
ON "default"
GO

CREATE
  TABLE Customer
  (
    idCustomer INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    fname      VARCHAR (100) NOT NULL ,
    lname      VARCHAR (100) NOT NULL ,
    type       VARCHAR (20) NOT NULL DEFAULT 'customer' ,
    company    VARCHAR (100) ,
    phone      VARCHAR (50) ,
    lastvisit  DATETIME ,
    CONSTRAINT Customer_PK PRIMARY KEY CLUSTERED (idCustomer)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
ALTER TABLE Customer
ADD
CHECK ( type IN ('admin', 'customer') )
GO
CREATE UNIQUE NONCLUSTERED INDEX
Customer__IDX ON Customer
(
idCustomer
)
ON "default"
GO

CREATE
  TABLE Login
  (
    idCustomer INTEGER NOT NULL ,
    email      VARCHAR (100) NOT NULL ,
    password   VARCHAR (300) NOT NULL ,
    CONSTRAINT Login_PK PRIMARY KEY CLUSTERED (idCustomer)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default" ,
  CONSTRAINT Login__UNv2 UNIQUE NONCLUSTERED (email) ON "default"
  )
  ON "default"
GO

CREATE
  TABLE "Order"
  (
    idOrder    INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    idCustomer INTEGER NOT NULL ,
    idDelivery INTEGER NOT NULL ,
    shipDate   DATETIME ,
    orderDate  DATETIME NOT NULL ,
    cost FLOAT NOT NULL ,
    status     VARCHAR (20) ,
    discount   INTEGER ,
    adress     VARCHAR (100) NOT NULL ,
    city       VARCHAR (100) NOT NULL ,
    postalcode VARCHAR (10) NOT NULL ,
    CONSTRAINT Order_PK PRIMARY KEY CLUSTERED (idOrder)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
ALTER TABLE "Order"
ADD
CHECK ( status IN ('odeslana', 'prijata', 'stornovana', 'zaplacena',
'zpracovana') )
GO
CREATE UNIQUE NONCLUSTERED INDEX
Order__IDX ON "Order"
(
idOrder
)
ON "default"
GO

CREATE
  TABLE OrderDetail
  (
    idOrder   INTEGER NOT NULL ,
    idProduct INTEGER NOT NULL ,
    quantity  INTEGER NOT NULL ,
    discount  INTEGER ,
    CONSTRAINT OrderDetail_PK PRIMARY KEY CLUSTERED (idOrder, idProduct)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Product
  (
    idProduct  INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    idCategory INTEGER NOT NULL ,
    name       VARCHAR (100) NOT NULL ,
    description NVARCHAR (MAX) ,
    currentCost FLOAT NOT NULL ,
    create_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    CONSTRAINT Product_PK PRIMARY KEY CLUSTERED (idProduct)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Product__IDX ON Product
(
  idProduct
)
ON "default"
GO

CREATE
  TABLE ProductCostHistory
  (
    idHistory INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    idProduct INTEGER NOT NULL ,
    starDate  DATETIME NOT NULL ,
    endDate   DATETIME NOT NULL ,
    cost FLOAT ,
    CONSTRAINT ProductCostHistory_PK PRIMARY KEY CLUSTERED (idHistory)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
ProductCostHistory__IDX ON ProductCostHistory
(
  idHistory
)
ON "default"
GO

CREATE
  TABLE TypeDelivery
  (
    idDelivery INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    name       VARCHAR (100) NOT NULL ,
    cost FLOAT NOT NULL ,
    CONSTRAINT TypeDelivery_PK PRIMARY KEY CLUSTERED (idDelivery)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
TypeDelivery__IDX ON TypeDelivery
(
  idDelivery
)
ON "default"
GO

CREATE
  TABLE WatchDog
  (
    idCustomer INTEGER NOT NULL ,
    idProduct  INTEGER NOT NULL ,
    createDate DATETIME NOT NULL ,
    cost FLOAT NOT NULL ,
    notify BIT NOT NULL ,
    CONSTRAINT WatchDog_PK PRIMARY KEY CLUSTERED (idCustomer, idProduct)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

ALTER TABLE Login
ADD CONSTRAINT Login_Customer_FK FOREIGN KEY
(
idCustomer
)
REFERENCES Customer
(
idCustomer
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE OrderDetail
ADD CONSTRAINT OrderDetail_Order_FK FOREIGN KEY
(
idOrder
)
REFERENCES "Order"
(
idOrder
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE OrderDetail
ADD CONSTRAINT OrderDetail_Product_FK FOREIGN KEY
(
idProduct
)
REFERENCES Product
(
idProduct
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE "Order"
ADD CONSTRAINT Order_Customer_FK FOREIGN KEY
(
idCustomer
)
REFERENCES Customer
(
idCustomer
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE "Order"
ADD CONSTRAINT Order_TypeDelivery_FK FOREIGN KEY
(
idDelivery
)
REFERENCES TypeDelivery
(
idDelivery
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE ProductCostHistory
ADD CONSTRAINT ProductCostHistory_Product_FK FOREIGN KEY
(
idProduct
)
REFERENCES Product
(
idProduct
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Product
ADD CONSTRAINT Product_Category_FK FOREIGN KEY
(
idCategory
)
REFERENCES Category
(
idCategory
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE WatchDog
ADD CONSTRAINT WatchDog_Customer_FK FOREIGN KEY
(
idCustomer
)
REFERENCES Customer
(
idCustomer
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE WatchDog
ADD CONSTRAINT WatchDog_Product_FK FOREIGN KEY
(
idProduct
)
REFERENCES Product
(
idProduct
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             6
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
